import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const logStep = (step: string, details?: any) => {
  console.log(`[GENERATE-RECRUITMENT-EMAIL] ${step}${details ? ` - ${JSON.stringify(details)}` : ''}`);
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    logStep("Starting recruitment email generation");

    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? ""
    );

    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("No authorization header");

    const token = authHeader.replace("Bearer ", "");
    const { data: userData, error: userError } = await supabaseClient.auth.getUser(token);
    if (userError) throw new Error(`Auth error: ${userError.message}`);
    const user = userData.user;
    if (!user) throw new Error("User not authenticated");

    logStep("User authenticated", { userId: user.id });

    // Check subscription
    const { data: subscription } = await supabaseClient
      .from('subscriptions')
      .select('plan_type')
      .eq('user_id', user.id)
      .single();

    if (subscription?.plan_type !== 'premium') {
      throw new Error('Premium subscription required for recruitment email generation');
    }

    const { recipientName, companyName, position, userBackground } = await req.json();
    
    // Get user profile
    const { data: profile } = await supabaseClient
      .from('profiles')
      .select('*')
      .eq('user_id', user.id)
      .single();

    logStep("Retrieved user profile and subscription");

    // Generate recruitment email with Gemini
    const geminiApiKey = Deno.env.get('GEMINI_API_KEY');
    if (!geminiApiKey) throw new Error('Gemini API key not configured');

    const prompt = `Generate a professional recruitment email based on the following information:

    From (Candidate):
    - Name: ${profile?.first_name || ''} ${profile?.last_name || ''}
    - Email: ${profile?.email || ''}
    - Background: ${userBackground}

    To (Recruiter):
    - Name: ${recipientName || 'Hiring Manager'}
    - Company: ${companyName}
    - Position: ${position}

    Please generate a professional, personalized recruitment email that:
    1. Has a compelling subject line suggestion
    2. Opens with a professional greeting
    3. Briefly introduces the candidate and their interest
    4. Highlights key qualifications relevant to the position
    5. Shows knowledge of and enthusiasm for the company
    6. Includes a clear call to action
    7. Ends with professional closing
    8. Is concise but impactful (2-3 short paragraphs)

    Format:
    Subject: [Suggested subject line]

    [Email body]

    Best regards,
    ${profile?.first_name || ''} ${profile?.last_name || ''}

    Return only the email content including the subject line suggestion.`;

    logStep("Calling Gemini API for recruitment email");

    const geminiResponse = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${geminiApiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{
            parts: [{ text: prompt }]
          }]
        })
      }
    );

    if (!geminiResponse.ok) {
      throw new Error(`Gemini API error: ${geminiResponse.status}`);
    }

    const geminiData = await geminiResponse.json();
    const generatedContent = geminiData.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedContent) {
      throw new Error('No content generated by Gemini');
    }

    logStep("Generated recruitment email with Gemini");

    // Save recruitment email to database
    const { data: recruitmentEmail, error: emailError } = await supabaseClient
      .from('recruitment_emails')
      .insert({
        user_id: user.id,
        recipient_name: recipientName,
        company_name: companyName,
        position: position,
        content: userBackground,
        generated_content: generatedContent
      })
      .select()
      .single();

    if (emailError) throw new Error(`Database error: ${emailError.message}`);

    logStep("Recruitment email saved to database", { emailId: recruitmentEmail.id });

    // Log generation
    await supabaseClient
      .from('generation_logs')
      .insert({
        user_id: user.id,
        type: 'recruitment_email',
        model_used: 'gemini-2.0-flash',
        status: 'completed'
      });

    return new Response(JSON.stringify({
      success: true,
      recruitmentEmail: recruitmentEmail,
      generated_content: generatedContent
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    });

  } catch (error) {
    logStep("ERROR", { message: error.message });
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 500,
    });
  }
});