// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjkplvxbcjatnvrcsmjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqa3BsdnhiY2phdG52cmNzbWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDg4NTcsImV4cCI6MjA2OTc4NDg1N30.uGuqCYfzOiPi9r7m-1EVFgVp7XLh93qgT8id9meWKWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});